### ISSUE TITLE
「地方の力を、企業の力に」がよろしくないのでは...?

### ISSUE THREAD

**Issue by style-arts** [style-arts/NIFP#40]
## 動機

NAGAOKA WORKERに人材を取られるという地元企業がうるさいらしい…

## 現状

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/104714748/219550599-5c2126ac-343b-4194-bd3e-3bb479700cb5.png">

## 対応策

「地方の力を、企業の力に」のコピーを全部削除してください

**Comment by kSaigusa** [comment]
わかりました
